// Mocks generated by Mockito 5.4.6 from annotations
// in flower_shop/test/app/features/auth/api/datasourse/auth_dataSource_imp_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flower_shop/app/core/api_manger/api_client.dart' as _i3;
import 'package:flower_shop/app/features/auth/data/models/request/forget_password_request_model/forget_password_request_model.dart'
    as _i6;
import 'package:flower_shop/app/features/auth/data/models/request/verify_reset_code_request_model/verify_reset_code_request.dart'
    as _i8;
import 'package:flower_shop/app/features/auth/data/models/response/forget_password_response_model/forget_password_response_model.dart'
    as _i5;
import 'package:flower_shop/app/features/auth/data/models/response/verify_reset_code_response_model/verify_reset_code_response_model.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:retrofit/retrofit.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHttpResponse_0<T> extends _i1.SmartFake
    implements _i2.HttpResponse<T> {
  _FakeHttpResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i3.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.HttpResponse<_i5.ForgotPasswordResponse>> forgotPassword(
    _i6.ForgotPasswordRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPassword, [request]),
            returnValue:
                _i4.Future<_i2.HttpResponse<_i5.ForgotPasswordResponse>>.value(
                  _FakeHttpResponse_0<_i5.ForgotPasswordResponse>(
                    this,
                    Invocation.method(#forgotPassword, [request]),
                  ),
                ),
          )
          as _i4.Future<_i2.HttpResponse<_i5.ForgotPasswordResponse>>);

  @override
  _i4.Future<_i2.HttpResponse<_i7.VerifyResetCodeResponse>> verifyResetCode(
    _i8.VerifyResetCodeRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetCode, [request]),
            returnValue:
                _i4.Future<_i2.HttpResponse<_i7.VerifyResetCodeResponse>>.value(
                  _FakeHttpResponse_0<_i7.VerifyResetCodeResponse>(
                    this,
                    Invocation.method(#verifyResetCode, [request]),
                  ),
                ),
          )
          as _i4.Future<_i2.HttpResponse<_i7.VerifyResetCodeResponse>>);
}
