name: Flutter Unit Tests Validation

on:
  pull_request:
    branches:
      - main
      - dev
      - Github-Actions
  push:
    branches:
      - main
      - dev
      - Github-Actions
jobs:
  test:
    name: Run Flutter Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        # removed flutter-version to allow any version for team flexibility

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run unit tests
        run: flutter test
