// Mocks generated by Mockito 5.4.6 from annotations
// in flower_shop/test/app/features/auth/data/repos/auth_repo_imp_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flower_shop/app/core/network/api_result.dart' as _i4;
import 'package:flower_shop/app/features/auth/data/datasoure/auth_datasource.dart'
    as _i2;
import 'package:flower_shop/app/features/auth/data/models/request/forget_password_request_model/forget_password_request_model.dart'
    as _i6;
import 'package:flower_shop/app/features/auth/data/models/response/forget_password_response_model/forget_password_response_model.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthDatasource extends _i1.Mock implements _i2.AuthDatasource {
  MockAuthDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i5.ForgotPasswordResponse>?> forgotPassword(
    _i6.ForgotPasswordRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPassword, [request]),
            returnValue:
                _i3.Future<_i4.ApiResult<_i5.ForgotPasswordResponse>?>.value(),
          )
          as _i3.Future<_i4.ApiResult<_i5.ForgotPasswordResponse>?>);
}
